import { Link } from 'react-router-dom';
import { Leaf, ArrowLeft } from 'lucide-react';

export default function AboutPage() {
  return (
    <div className="home-page">
      <nav className="home-navbar">
        <div className="home-logo">
          <div className="home-logo-icon">
            <Leaf size={24} color="white" />
          </div>
          <span className="home-logo-text">AnnaSetu</span>
        </div>
        <div className="home-nav-links">
          <Link to="/">Home</Link>
          <Link to="/login" className="btn btn-primary">Sign In</Link>
        </div>
      </nav>

      <section className="section" style={{ paddingTop: '120px', maxWidth: '800px', margin: '0 auto' }}>
        <Link to="/" className="btn btn-ghost btn-sm" style={{ marginBottom: '24px' }}>
          <ArrowLeft size={16} /> Back to Home
        </Link>
        
        <h1 className="hero-title" style={{ fontSize: '2.5rem', textAlign: 'left', marginBottom: '24px' }}>
          About <span className="text-gradient">AnnaSetu</span>
        </h1>
        
        <div className="glass-card-static" style={{ marginBottom: '32px' }}>
          <h3 style={{ marginBottom: '16px', color: 'var(--color-teal)' }}>The Problem</h3>
          <p style={{ color: 'var(--color-text-secondary)', lineHeight: '1.8' }}>
            Food waste has emerged as one of the most pressing global challenges. In cities like Bhopal, 
            significant amounts of surplus food generated by restaurants, hotels, and events remain edible 
            but are discarded due to the absence of an efficient redistribution mechanism. Meanwhile, many 
            people still experience food insecurity.
          </p>
        </div>
        
        <div className="glass-card-static" style={{ marginBottom: '32px' }}>
          <h3 style={{ marginBottom: '16px', color: 'var(--color-violet)' }}>Our Solution</h3>
          <p style={{ color: 'var(--color-text-secondary)', lineHeight: '1.8', marginBottom: '16px' }}>
            AnnaSetu (Smart Food Waste Management System) is a web-based platform designed to facilitate 
            efficient redistribution of surplus food from donors to nearby Non-Governmental Organizations (NGOs) in Bhopal.
          </p>
          <p style={{ color: 'var(--color-text-secondary)', lineHeight: '1.8' }}>
            The system enables donors to register and upload food donation details, while authenticated NGOs 
            receive real-time notifications regarding available donations. This replaces slow manual communication 
            methods and ensures food reaches those in need before it spoils.
          </p>
        </div>
        
        <div className="glass-card-static" style={{ marginBottom: '32px' }}>
          <h3 style={{ marginBottom: '16px', color: 'var(--color-amber)' }}>SDG Alignment</h3>
          <ul style={{ color: 'var(--color-text-secondary)', lineHeight: '1.8', paddingLeft: '20px' }}>
            <li style={{ marginBottom: '8px' }}>
              <strong>SDG 2 (Zero Hunger):</strong> By facilitating the redistribution of surplus food to underprivileged communities.
            </li>
            <li>
              <strong>SDG 12 (Responsible Consumption and Production):</strong> By minimizing food wastage and promoting efficient resource utilization.
            </li>
          </ul>
        </div>
        
        <div className="glass-card-static">
          <h3 style={{ marginBottom: '16px', color: 'var(--color-blue)' }}>Project By</h3>
          <p style={{ color: 'var(--color-text-secondary)', lineHeight: '1.8' }}>
            <strong>Swetha B S</strong> (Assistant Professor)<br />
            <strong>Pavana S</strong> (Student)<br />
            Department of Computer Science and Engineering<br />
            P.E.S College of Engineering, Mandya
          </p>
        </div>
      </section>
    </div>
  );
}
